name: zero-enter-antifraud
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - PyYAML
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - numpy=1.21.6
  - networkx=2.6.3
  - scipy=1.7.3
  - pytorch=1.12.1
  - matplotlib
  - jupyter
  - onnx
  - pip:
      - ezkl